Finish merging with the original Wyvern repository
RackDevelopment/Wyvern2 pull request #3
Opened 2022-02-08 07:31 UTC by WyvernPJ

Up-to-date all the scripts with the original Wyvern repository.

2022-02-08 09:20 UTC, WyvernPJ commented
if you merge it just copy directly the name of the commit, that is readable than just `Merging pull request #n from something`

2022-02-08 17:46 UTC, RackDevelopment requested changes
Looks good besides the J16 mention rathe than 17 mentioned.

2022-02-08 17:46 UTC, RackDevelopment commented on pom.xml
> -        <maven.compiler.source>17</maven.compiler.source>
Please update compiler source to Java 17, rather than 16.

2022-02-08 17:47 UTC, RackDevelopment commented on pom.xml
> +        <maven.compiler.target>16</maven.compiler.target>
Java 16 Call, should be J17

2022-02-08 18:31 UTC, RackDevelopment commented on patches/api/0001-Wyvern-API-POM.patch
> ++    <groupId>com.wyvern</groupId>
Please revert back to tech.rackdevelopment.wyvern for the groupID, I am only pointing this one out but I am aware there are other files that contain it as well.

2022-02-08 22:50 UTC, WyvernPJ commented
@RackDevelopment ill just gonna make a commit fixing these later if you are okay with me pushing it directly

2022-02-09 00:14 UTC, RackDevelopment commented
Id prefer if you just add the commit here, if you cant, go ahead.

2022-02-09 14:20 UTC, merged